package horarios;
// Generated 14-abr-2019 22:38:10 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.persistence.OneToMany;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

    private int idAsignatura;
    private String nombre;
    private int cuatrimestre;
    private int curso;
    @OneToMany
    private Set horas = new HashSet(0);

    public Asignatura() {
    }

    public Asignatura(int idAsignatura, String nombre, int cuatrimestre, int curso) {
        this.idAsignatura = idAsignatura;
        this.nombre = nombre;
        this.cuatrimestre = cuatrimestre;
        this.curso = curso;
    }

    public Asignatura(int idAsignatura, String nombre, int cuatrimestre, int curso, Set horas) {
        this.idAsignatura = idAsignatura;
        this.nombre = nombre;
        this.cuatrimestre = cuatrimestre;
        this.curso = curso;
        this.horas = horas;
    }

    public int getIdAsignatura() {
        return this.idAsignatura;
    }

    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getCuatrimestre() {
        return this.cuatrimestre;
    }

    public void setCuatrimestre(int cuatrimestre) {
        this.cuatrimestre = cuatrimestre;
    }

    public int getCurso() {
        return this.curso;
    }

    public void setCurso(int curso) {
        this.curso = curso;
    }

    public Set getHoras() {
        return this.horas;
    }

    public void setHoras(Set horas) {
        this.horas = horas;
    }

    public List<Hora> getHorarioTeoria() {
        List<Hora> horasTeoria = new ArrayList<>();

        for (Iterator<Hora> it = horas.iterator(); it.hasNext();) {

            Hora nueva = it.next();
            if (nueva.getTipo() == 0) {
                horasTeoria.add(nueva);
            }
        }

        return horasTeoria;
    }

    public List<Hora> getHorarioPractica() {
        
        List<Hora> horasPracticas = new ArrayList<>();

        for (Iterator<Hora> it = horas.iterator(); it.hasNext();) {

            Hora nueva = it.next();
            if (nueva.getTipo() == 1) {
                horasPracticas.add(nueva);
            }
        }

        return horasPracticas;
    }

}
