package horarios;
// Generated 14-abr-2019 22:38:10 by Hibernate Tools 4.3.1

/**
 * HoraId generated by hbm2java
 */
public class HoraId implements java.io.Serializable {

    private String idHora;
    private int asignaturaIdAsignatura;

    public HoraId() {
    }

    public HoraId(String idHora, int asignaturaIdAsignatura) {
        this.idHora = idHora;
        this.asignaturaIdAsignatura = asignaturaIdAsignatura;
    }

    public String getIdHora() {
        return this.idHora;
    }

    public void setIdHora(String idHora) {
        this.idHora = idHora;
    }

    public int getAsignaturaIdAsignatura() {
        return this.asignaturaIdAsignatura;
    }

    public void setAsignaturaIdAsignatura(int asignaturaIdAsignatura) {
        this.asignaturaIdAsignatura = asignaturaIdAsignatura;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof HoraId)) {
            return false;
        }
        HoraId castOther = (HoraId) other;

        return ((this.getIdHora() == castOther.getIdHora()) || (this.getIdHora() != null && castOther.getIdHora() != null && this.getIdHora().equals(castOther.getIdHora())))
                && (this.getAsignaturaIdAsignatura() == castOther.getAsignaturaIdAsignatura());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getIdHora() == null ? 0 : this.getIdHora().hashCode());
        result = 37 * result + this.getAsignaturaIdAsignatura();
        return result;
    }

}
