/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horarios;

import java.util.List;

/**
 *
 * @author Juan
 */
public class VentanaHorario extends javax.swing.JFrame
{

    List<Hora> horario;
    /**
     * Creates new form VentanaHorario
     */
    public VentanaHorario(List<Hora> horario)
    {
        initComponents();
        this.horario=horario;
        mostrarHorario(horario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AreaHorarios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        AreaHorarios.setColumns(20);
        AreaHorarios.setRows(5);
        jScrollPane1.setViewportView(AreaHorarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    
    public void mostrarHorario(List<Hora> horario) {
        //System.out.println("---- HORARIO ----");
        StringBuffer salida=new StringBuffer();
        String nuevo ="";
        
        nuevo ="---- HORARIO ----"+ "\n";
        nuevaCadena(salida, nuevo);
        

        for (int cuatrimestre = 1; cuatrimestre < 3; cuatrimestre++) {
            //System.out.println("\n---- CUATRIMESTRE " + cuatrimestre + " ---");
            
            nuevo ="\n---- CUATRIMESTRE " + cuatrimestre + " ---"+ "\n";
            nuevaCadena(salida, nuevo);
            for (int i = 0; i < horario.size(); i++) {
                if (horario.get(i).getAsignatura().getCuatrimestre() == cuatrimestre) {
                    //System.out.println("\n" + horario.get(i).getAsignatura().getNombre());
                    nuevaCadena(salida, nuevo);

                    nuevo="\n---- CUATRIMESTRE " + cuatrimestre + " ---"+ "\n";
                    nuevaCadena(salida, nuevo);
                    
                    if (horario.get(i).getTipo() == 0) {
                        //System.out.println("TEORIA");
                        nuevo="TEORIA"+ "\n";
                        
                    } else {
                        //System.out.println("PRACTICA");
                        nuevo="PRACTICA"+ "\n";
                    }
                    nuevaCadena(salida, nuevo);

                    switch (horario.get(i).getDia()) {
                        case 1:
                            //System.out.println("lunes " + horario.get(i).getHInicio());
                            nuevo="lunes " + horario.get(i).getHInicio()+ "\n";
                            break;
                        case 2:
                            //System.out.println("Martes " + horario.get(i).getHInicio());
                            nuevo="Martes" + horario.get(i).getHInicio()+ "\n";
                            break;
                        case 3:
                            //System.out.println("Miércoles " + horario.get(i).getHInicio());
                            nuevo="Miércoles " + horario.get(i).getHInicio()+ "\n";
                            break;
                        case 4:
                            //System.out.println("Jueves " + horario.get(i).getHInicio());
                            nuevo="Jueves " + horario.get(i).getHInicio()+ "\n";
                            break;
                        default:
                            //System.out.println("Viernes " + horario.get(i).getHInicio());
                            nuevo="Viernes " + horario.get(i).getHInicio()+ "\n";
                            break;
                    }
                    nuevaCadena(salida, nuevo);
                }
            }
        }
        AreaHorarios.setText(salida.toString());
        
    }
    
    public StringBuffer nuevaCadena(StringBuffer cadena, String nuevo){
        cadena.append(nuevo);
        return cadena;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaHorarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
